---
- name: 'update apt packages.'
  become: yes
  apt:
    update_cache: yes

- name: 'upgrade packages'
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: 'Install Node.js 13'
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: 'install node 13'
  become: yes
  apt:
    name: [nodejs]
    state: latest
    update_cache: yes

- name: 'install pm2'
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
    production: yes
