---
- name: copy backend zipped file
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: unzipped backend
  shell: |
    mkdir backend
    tar -C backend -xf artifact.tar.gz

- name: add .env file in backend
  template:
    src: .environment
    dest: ~/backend/.env

- name: start the app
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
