---
- name: copy backend zipped file
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: 'Create backend directory'
  file:
    path: ~/backend
    state: directory

- name: 'Unarchive files'
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: add .env file in backend
  template:
    src: .environment
    dest: ~/backend/.env

- name: start the app
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
